[package]
name = "libsignal-service"
version = "0.1.0"
authors = ["Michael Bryan <michaelfbryan@gmail.com>", "Shady Khalifa <shekohex@gmail.com>"]
edition = "2018"
license = "GPLv3"
readme = "../README.md"

[dependencies]
libsignal-protocol = { git = "https://github.com/Michael-F-Bryan/libsignal-protocol-rs" }
failure = "0.1.5"
async-trait = "0.1.30"
url = "2.1.1"
thiserror = "1.0"
serde = {version = "1.0", features=["derive"]}
prost = "0.6"
http = "0.2.1"

[dev-dependencies]
structopt = "0.2.17"
tokio = { version = "0.2", features=["macros"] }

[build-dependencies]
prost-build = "0.6"
